version: '3.2'

services:
  redis:
    container_name: redis
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - ./data:/data
